# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "22ed644d45dd3afc6053fe8528404a89"
name = "Variant Description"
handle = "variant-description-8"
application_url = "https://given-various-biol-venues.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "timeless-tune.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions"

[auth]
redirect_urls = [
  "https://given-various-biol-venues.trycloudflare.com/auth/callback",
  "https://given-various-biol-venues.trycloudflare.com/auth/shopify/callback",
  "https://given-various-biol-venues.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
